// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_Screen2;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1415182567);    // assets\Curves-2.png
LV_IMG_DECLARE(ui_img_1712731771);    // assets\blue-background.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
